### ISSUE TITLE
[Question] What about hot reloading?

### ISSUE THREAD

**Issue by tatemz** [electrode-io/electrode-archetype-react-app#33]
Is there any plan to incorporate [hot reloading](http://gaearon.github.io/react-hot-loader/) into the dev servers?

**Comment by jchip** [comment]
it's supported with `gulp hot`.

There's an issue with source map at the moment using hot reloading though.

**Comment by ananavati** [comment]
hot-reloading of jsx is already built-in and `gulp hot` will enable hot-reloading of jsx.
![out](https://cloud.githubusercontent.com/assets/360041/19363473/7de8f73e-913f-11e6-9c5a-16da17284592.gif)

**Comment by tatemz** [comment]
Thanks. I read through the documentation, but I fall prey to not having my cognitive resources drained: https://www.youtube.com/watch?v=FKTxC9pl-WM
