### ISSUE TITLE
Upgrade to eslint@3.0

### ISSUE THREAD

**Issue by joonki34** [electrode-io/electrode-archetype-react-app#36]
I can't use "off", "warn" or "error" for lint rules because eslint gives me errors. The error message is `Value "off" is the wrong type.`

I think this is because eslint version for the archetype is 1.+. Do you guys have a plan to upgrade eslint to 3.+?

Thanks.

**Comment by caoyangs** [comment]
Yes, it's in our backlog. https://github.com/electrode-io/electrode-archetype-react-component/issues/3
