### ISSUE TITLE
How to load the css inside the node_module for the 3rd party react component 

### ISSUE THREAD

**Issue by bubuzzz** [electrode-io/electrode-archetype-react-app#43]
For some 3rd react components (for example: https://github.com/pqx/react-ui-tree/tree/master/dist ), the css file is not included into the component itself, thus we have to include it manually into our Layout.jsx 

`import 'node_modules/react-ui-tree/dist/react-ui-tree.css`

However, when using this way, the css file is bundled and mapped to the different class names, thus making the component does not render correctly. How can we include 3rd css file so the file become global scope and the 3rd party component can be effected ? 

Our current workaround is host those css files remotely or make a plugin in order to return the correct file  on the hapi server and import it back to the base.css 

`@import url(//maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css)`

so the file is not bundled anymore, but I don't think it is a good idea

**Comment by ananavati** [comment]
Electrode comes pre-built with [CSS Modules](https://github.com/css-modules/css-modules) and compile/bundle settings related to CSSNext + CSSModules + PostCSS and hence supporting the global namespace of CSS is not supported.

Unfortunately supporting 3rd party compiled CSS will work when importing using the CSS Modules namespaced scoping or loading CSS from an external source.
